### ISSUE TITLE
使用时遇到点问题

### ISSUE THREAD

**Issue by ktangel** [LuoLiangDSGA/spring-learning#14]
1。
现在用的是Antdv的Admin的模板，引入 你的插件并Use之后。
在页面中的表单里使用。
提示错误：
this.xhr.upload.addEventListener is not a function

所以是不是你有些方法的this没有强得绑定到你插件里面的对象，导致单独作为表单中的组件 中使用时，this上下文指向出问题。
2，然后建议演示实例用原生的一些控件或者Vue的antd或者eleme的组件 演示也行，用Slot覆盖的话，能让使用模板的同学现方便用自己的样式插入你的组件 中。

**Comment by LuoLiangDSGA** [comment]
这个demo只是为了实现上传的功能，如果有需要可以自行修改，我是一名后端攻城狮😁
