### ISSUE TITLE
Docker基础镜像

### ISSUE THREAD

**Issue by tillend** [LuoLiangDSGA/Spring-Learning#2]
留意到boot-dubbo项目中使用了Dockerfile，而其中的基础镜像为java8。推荐基础镜像需要java环境时最好使用openJDK,如openjdk:8-jdk-alpine，因为oracle可能会“不喜欢”

**Comment by LuoLiangDSGA** [comment]
boot-dubbo中的Dockerfile实际上没有使用，谢谢提醒！
