### ISSUE TITLE
boot-uploader上传含中文路径文件夹uniqueIdentifier有问题；文件名含'-'merge时bug.

### ISSUE THREAD

**Issue by xiangyang1602** [LuoLiangDSGA/spring-learning#4]
Files.list(Paths.get(folder))
                    .filter(path -> !path.equals(Paths.get(targetFile)))
                    .filter(path -> path.getFileName().toString().contains("-"))
                    .sorted((o1, o2) -> {
                        String p1 = o1.getFileName().toString();
                        String p2 = o2.getFileName().toString();
                        int i1 = p1.lastIndexOf("-");
                        int i2 = p2.lastIndexOf("-");
                        return Integer.valueOf(p2.substring(i2)).compareTo(Integer.valueOf(p1.substring(i1)));
                    })
                    .forEach(path -> {
                        try {
                            //以追加的形式写入文件
                            Files.write(Paths.get(targetFile), Files.readAllBytes(path), StandardOpenOption.APPEND);
                            //合并后删除该块
                            Files.delete(path);
                        } catch (IOException e) {
                            logger.error(e.getMessage(), e);
                        }
                    });

**Comment by LuoLiangDSGA** [comment]
已修复
